export * from './Authenticaion';
export * from './CreateNewPassword';
export * from './ForgetPassword';
export * from './Login';
export * from './Parents';
export * from './User';
export * from './UserActive';
export * from './UserDiplomas';
export * from './UserInternship';
